- `pd.read_json(file_path, orient="records")`: Reads Json file and returns a pandas DataFrame
    - *file_path*: Path to csv file
    - *orient*: indication of expected JSON string format

In [1]:
import pandas as pd

In [2]:
users_df = pd.read_json("../data/users.json")
users_df.shape

(12, 5)

## Accessing Data

In [3]:
users_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             12 non-null     int64
 1   name           12 non-null     str
 2   is_active      12 non-null     bool
 3   roles          12 non-null     object
 4   premium_since  7 non-null      str
dtypes: bool(1), int64(1), object(1), str(2)
memory usage: 528.0+ bytes

In [4]:
users_df.head()

    id           name  is_active                     roles premium_since
0  101  Alice Johnson       True           [admin, editor]           NaN
1  102      Bob Smith       True                  [viewer]    2024-03-15
2  103  Carlos Mendez      False                  [editor]           NaN
3  104   Diana Prince       True  [admin, billing_manager]    2023-11-01
4  105    Evan Wright       True     [viewer, contributor]    2025-01-10

In [5]:
users_df.isnull()

       id   name  is_active  roles  premium_since
0   False  False      False  False           True
1   False  False      False  False          False
2   False  False      False  False           True
3   False  False      False  False          False
4   False  False      False  False          False
5   False  False      False  False           True
6   False  False      False  False          False
7   False  False      False  False           True
8   False  False      False  False          False
9   False  False      False  False          False
10  False  False      False  False          False
11  False  False      False  False           True

In [6]:
users_df.tail()

     id           name  is_active                 roles premium_since
7   108  Hannah Abbott       True         [contributor]           NaN
8   109    Ian Malcolm       True               [admin]    2022-06-30
9   110  Julia Roberts      False              [viewer]    2023-04-12
10  111    Kevin Bacon       True    [editor, reviewer]    2025-05-18
11  112  Luna Lovegood       True  [viewer, subscriber]           NaN