## Reading Data From Excel Files

- `pd.read_excel(file_path, sheet_name=0)`: Reads an Excel file and returns a Pandas DataFrame
  - *file_path*: Path to the Excel file
  - *sheet_name*: Name or index of the Excel sheet to read (default is `0`, meaning the first sheet)

In [1]:
import pandas as pd

In [2]:
sc_df = pd.read_excel("../data/Supply_Chain.xlsx", sheet_name=0)
sc_df.shape

(1000, 11)

In [3]:
sc_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Shipment ID       1000 non-null   str
 1   Order Date        1000 non-null   datetime64[us]
 2   Supplier Name     1000 non-null   str
 3   Product Category  1000 non-null   str
 4   Quantity          1000 non-null   int64
 5   Total Cost        1000 non-null   float64
 6   Ship Date         1000 non-null   datetime64[us]
 7   Delivery Date     1000 non-null   datetime64[us]
 8   Shipping Carrier  1000 non-null   str
 9   Shipping Mode     1000 non-null   str
 10  On-Time Delivery  1000 non-null   str
dtypes: datetime64[us](3), float64(1), int64(1), str(6)
memory usage: 86.1 KB

In [4]:
sc_df.head()

,Shipment ID,Order Date,Supplier Name,Product Category,Quantity,Total Cost,Ship Date,Delivery Date,Shipping Carrier,Shipping Mode,On-Time Delivery
0,SHP-40001,2024-07-06,Frontier Chemical Supply,Chemicals,2968,771.78,2024-07-08,2024-08-21,UPS,Sea,No
1,SHP-40002,2025-02-19,Midwest Industrial,Packaging,2059,1960.20,2025-02-22,2025-02-24,UPS,Road,Yes
2,SHP-40003,2025-10-26,Summit Electronics,Chemicals,4046,3253.23,2025-10-29,2025-11-16,FedEx,Sea,Yes
3,SHP-40004,2024-12-31,Continental Distributors,Machinery,4494,6248.57,2025-01-02,2025-01-09,Local,Road,Yes
4,SHP-40005,2024-04-20,Reliable Metals Corp,Automotive Parts,927,6853.79,2024-04-22,2024-04-28,UPS,Road,Yes

In [5]:
sc_df.tail()

,Shipment ID,Order Date,Supplier Name,Product Category,Quantity,Total Cost,Ship Date,Delivery Date,Shipping Carrier,Shipping Mode,On-Time Delivery
995,SHP-40996,2025-04-27,Nordic Supply Group,Food Ingredients,1404,606.85,2025-04-29,2025-05-12,UPS,Rail,No
996,SHP-40997,2024-09-13,Global Parts Inc,Machinery,2903,15781.34,2024-09-14,2024-09-24,FedEx,Road,No
997,SHP-40998,2025-06-12,Premier Raw Materials,Medical Supplies,4265,13505.40,2025-06-15,2025-06-20,UPS,Rail,Yes
998,SHP-40999,2024-03-23,Harbor Trading Co,Office Supplies,4235,2373.41,2024-03-26,2024-03-27,DHL,Air,Yes
999,SHP-41000,2024-07-17,Valley Fabrication,Raw Materials,655,4379.69,2024-07-20,2024-07-21,FedEx,Air,Yes

In [6]:
second_row = sc_df.loc[2]
second_row

Shipment ID                   SHP-40003
Order Date          2025-10-26 00:00:00
Supplier Name        Summit Electronics
Product Category              Chemicals
Quantity                           4046
Total Cost                      3253.23
Ship Date           2025-10-29 00:00:00
Delivery Date       2025-11-16 00:00:00
Shipping Carrier                  FedEx
Shipping Mode                       Sea
On-Time Delivery                    Yes
Name: 2, dtype: object

In [7]:
sc_df.describe()

,Order Date,Quantity,Total Cost,Ship Date,Delivery Date
count,1000,1000.000000,1000.000000,1000,1000
mean,2024-12-25 01:09:07.200000,2398.051000,8275.966820,2024-12-27 02:26:52.800000,2025-01-05 14:44:09.600000
min,2024-01-01 00:00:00,10.000000,94.500000,2024-01-03 00:00:00,2024-01-09 00:00:00
25%,2024-06-23 18:00:00,1158.750000,2397.087500,2024-06-25 18:00:00,2024-07-06 00:00:00
50%,2024-12-21 00:00:00,2336.000000,5030.890000,2024-12-23 00:00:00,2025-01-02 00:00:00
75%,2025-06-26 06:00:00,3608.000000,10820.422500,2025-06-28 06:00:00,2025-07-06 06:00:00
max,2025-12-29 00:00:00,4996.000000,49499.190000,2025-12-31 00:00:00,2026-01-30 00:00:00
std,NaN,1433.064285,9118.206662,NaN,NaN